# Generated by Django 5.1.1 on 2024-10-12 01:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anciano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('edad', models.IntegerField()),
                ('direccion', models.CharField(max_length=255)),
                ('genero', models.CharField(max_length=10)),
                ('numero_telefono', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('code', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('code', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('gender', models.CharField(max_length=10)),
                ('role', models.CharField(blank=True, max_length=100, null=True)),
                ('isactive', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContactoEmergencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_familiar', models.CharField(max_length=100)),
                ('relacion', models.CharField(max_length=50)),
                ('numero_telefono', models.CharField(max_length=15)),
                ('direccion', models.CharField(max_length=255)),
                ('genero', models.CharField(max_length=10)),
                ('anciano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contactos', to='CatedraAdultoMayor.anciano')),
            ],
        ),
        migrations.CreateModel(
            name='Enfermedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_enfermedad', models.CharField(max_length=255)),
                ('fecha_diagnostico', models.DateField()),
                ('descripcion', models.TextField()),
                ('medicamento', models.CharField(max_length=255)),
                ('anciano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enfermedades', to='CatedraAdultoMayor.anciano')),
            ],
        ),
        migrations.CreateModel(
            name='RoleAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('haveedit', models.BooleanField(default=False)),
                ('haveadd', models.BooleanField(default=False)),
                ('havedelete', models.BooleanField(default=False)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CatedraAdultoMayor.menu')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CatedraAdultoMayor.role')),
            ],
        ),
    ]
