# Generated by Django 5.1.1 on 2024-09-23 08:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CatedraAdultoMayor', '0002_contactoemergencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enfermedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_enfermedad', models.CharField(max_length=255)),
                ('fecha_diagnostico', models.DateField()),
                ('anciano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enfermedades', to='CatedraAdultoMayor.anciano')),
            ],
        ),
    ]
