# Generated by Django 5.1.1 on 2024-10-08 03:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CatedraAdultoMayor', '0003_enfermedad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('gender', models.CharField(max_length=10)),
                ('role', models.CharField(max_length=20)),
                ('isactive', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='RoleAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('haveedit', models.BooleanField()),
                ('haveadd', models.BooleanField()),
                ('havedelete', models.BooleanField()),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CatedraAdultoMayor.menu')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CatedraAdultoMayor.role')),
            ],
        ),
    ]
