# Generated by Django 5.1.1 on 2024-10-08 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CatedraAdultoMayor', '0004_menu_role_user_roleaccess'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='code',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='menu',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='role',
            name='code',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='roleaccess',
            name='haveadd',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='roleaccess',
            name='havedelete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='roleaccess',
            name='haveedit',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='isactive',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
